services:
  - type: web
    name: employee-mvc-docker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__EmployeeInfoDbConnection
        sync: false
      - key: ConnectionStrings__EmployeeAttendanceInfoDbConnection
        sync: false
    healthCheckPath: /
    autoDeploy: true
