services:
  - type: web
    name: employee-mvc-app
    env: dotnet
    buildCommand: |
      cd EmployeeInformations
      dotnet restore
      dotnet publish -c Release -o ../publish
    startCommand: |
      cd ./publish
      dotnet EmployeeInformations.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__EmployeeInfoDbConnection
        sync: false
      - key: ConnectionStrings__EmployeeAttendanceInfoDbConnection
        sync: false
